// Objeto con los botones del dashboard...

export const buttonIconTextData = [
  {
    'id': 0,
    'name': 'Dashboard',
    'icon': 'dashboard',
    'route': '/',
    'active': false,
    'type': 'normal',
  },
  {
    'id': 1,
    'name': 'Ventas',
    'icon': 'shopping_bag',
    'route': '/ventas',
    'active': false,
    'type': 'normal',
  },
  {
    'id': 2,
    'name': 'Compras',
    'icon': 'local_grocery_store',
    'route': '/compras',
    'active': false,
    'type': 'normal',
  },
  {
    'id': 3,
    'name': 'Bancos',
    'icon': 'account_balance',
    'route': '/bancos',
    'active': false,
    'type': 'normal',
  },
  {
    'id': 4,
    'name': 'Contabilidad',
    'icon': 'assessment',
    'route': '/contabilidad',
    'active': false,
    'type': 'normal',
  },
  {
    'id': 5,
    'name': 'Inventarios',
    'icon': 'inventory',
    'route': '/inventarios',
    'active': false,
    'type': 'normal',
  },
  {
    'id': 6,
    'name': 'Reportes',
    'icon': 'article',
    'route': '/reportes',
    'active': false,
    'type': 'normal',
  },
  {
    'id': 7,
    'name': 'Cliente/Proveedor',
    'icon': 'people',
    'route': '/proveedores',
    'active': false,
    'type': 'normal',
  },
  {
    'id': 8,
    'name': 'Tu Empresa',
    'icon': 'apartment',
    'route': '/empresa',
    'active': false,
    'type': 'acordeon',
  },
]
